const colors = {
  light: {
    text: '#0D0B1A',
    tint: '#6C5CE7',
    background: '#F5F4FF',
    foreground: '#0D0B1A',
    card: '#FFFFFF',
    cardForeground: '#0D0B1A',
    primary: '#6C5CE7',
    primaryForeground: '#FFFFFF',
    secondary: '#EDE9FF',
    secondaryForeground: '#4A3DC9',
    muted: '#F0EEFF',
    mutedForeground: '#7B7298',
    accent: '#00C9A7',
    accentForeground: '#FFFFFF',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#E2DDFF',
    input: '#EDE9FF',
    warning: '#FFA94D',
    success: '#51CF66',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#9B8FFF',
    background: '#0B0B18',
    foreground: '#FFFFFF',
    card: '#141428',
    cardForeground: '#FFFFFF',
    primary: '#7B6EFA',
    primaryForeground: '#FFFFFF',
    secondary: '#1E1E38',
    secondaryForeground: '#C0B8FF',
    muted: '#1A1A2E',
    mutedForeground: '#7070A0',
    accent: '#00D4AA',
    accentForeground: '#000000',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#252540',
    input: '#1E1E3A',
    warning: '#FFA94D',
    success: '#51CF66',
  },
  radius: 16,
};

export default colors;
